name: test_no_cache

on:
  pull_request:
    branches:
      - main

jobs:
  ci_no_cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up python
        uses: actions/setup-python@v4
        with:
          cache: "pip"
#          cache-dependency-path: "pyproject.toml"
#          python-version: 3.9

      - name: install
        run: pip install -e .[dev]

      - name: mypy
        run: ./scripts/lint.sh
